export class Client{
    id:string='';
    name:string='';
    email:string="";
    password:string="";
    phone:string='';
    image:string='';
}

export const CLIENTS:Client[]=[
    {
        id:"12",
        name:'Name',
        email:'as@fg.com',
        password:'rty',
        phone:'123456789',
        image:'/assets/images/product_image.jpg'
    },
    {
        id:"12",
        name:'Name',
        email:'as@fg.com',
        password:'rty',
        phone:'123456789',
        image:'/assets/images/product_image.jpg'
    },
    {
        id:"12",
        name:'Name',
        email:'as@fg.com',
        password:'rty',
        phone:'123456789',
        image:'/assets/images/product_image.jpg'
    },
    {
        id:"12",
        name:'Name',
        email:'as@fg.com',
        password:'rty',
        phone:'123456789',
        image:'/assets/images/product_image.jpg'
    }
];